// Comprehensive SAT/TOEFL/TEPS Level Vocabulary Database
export const SAT_VOCABULARY = [
  // Academic & Analysis Words (중요!)
  { word: "analyze", definition: "examine methodically and in detail", difficulty: "보통", type: "verb" },
  { word: "synthesize", definition: "combine elements to form a connected whole", difficulty: "어려움", type: "verb" },
  { word: "interpret", definition: "explain the meaning of information or actions", difficulty: "보통", type: "verb" },
  { word: "imply", definition: "strongly suggest the truth or existence of something", difficulty: "보통", type: "verb" },
  { word: "infer", definition: "deduce or conclude from evidence and reasoning", difficulty: "보통", type: "verb" },
  { word: "emphasize", definition: "give special importance or prominence to something", difficulty: "보통", type: "verb" },
  { word: "illustrate", definition: "explain or make something clear by using examples", difficulty: "보통", type: "verb" },
  { word: "demonstrate", definition: "clearly show the existence or truth of something", difficulty: "보통", type: "verb" },
  { word: "suggest", definition: "put forward for consideration", difficulty: "보통", type: "verb" },
  { word: "indicate", definition: "point out; show; be a sign of", difficulty: "보통", type: "verb" },
  { word: "contrast", definition: "compare in such a way as to emphasize differences", difficulty: "보통", type: "verb" },
  { word: "compare", definition: "estimate, measure similarities and differences", difficulty: "보통", type: "verb" },
  
  // High-Level Adjectives
  { word: "ambiguous", definition: "open to more than one interpretation; unclear", difficulty: "어려움", type: "adjective" },
  { word: "ambivalent", definition: "having mixed feelings or contradictory ideas", difficulty: "어려움", type: "adjective" },
  { word: "arbitrary", definition: "based on random choice rather than reason", difficulty: "어려움", type: "adjective" },
  { word: "chronic", definition: "persisting for a long time or constantly recurring", difficulty: "어려움", type: "adjective" },
  { word: "comprehensive", definition: "complete; including all elements", difficulty: "보통", type: "adjective" },
  { word: "conventional", definition: "based on what is generally done or believed", difficulty: "보통", type: "adjective" },
  { word: "crucial", definition: "of great importance; critical", difficulty: "보통", type: "adjective" },
  { word: "diverse", definition: "showing a great deal of variety", difficulty: "보통", type: "adjective" },
  { word: "explicit", definition: "stated clearly and in detail", difficulty: "보통", type: "adjective" },
  { word: "fundamental", definition: "forming a necessary base or core", difficulty: "보통", type: "adjective" },
  { word: "inevitable", definition: "certain to happen; unavoidable", difficulty: "어려움", type: "adjective" },
  { word: "inherent", definition: "existing as a natural or essential characteristic", difficulty: "어려움", type: "adjective" },
  { word: "innovative", definition: "featuring new methods; advanced and original", difficulty: "보통", type: "adjective" },
  { word: "negligible", definition: "so small or unimportant as to be not worth considering", difficulty: "어려움", type: "adjective" },
  { word: "persistent", definition: "continuing firmly despite opposition or difficulty", difficulty: "보통", type: "adjective" },
  { word: "prominent", definition: "important; famous; projecting from something", difficulty: "보통", type: "adjective" },
  { word: "profound", definition: "very great or intense; showing deep insight", difficulty: "어려움", type: "adjective" },
  { word: "substantial", definition: "of considerable importance, size, or worth", difficulty: "보통", type: "adjective" },
  { word: "significant", definition: "sufficiently great or important to be worthy of attention", difficulty: "보통", type: "adjective" },
  { word: "subtle", definition: "delicate or faint; not immediately obvious", difficulty: "어려움", type: "adjective" },
  { word: "vigorous", definition: "strong, healthy, and full of energy", difficulty: "보통", type: "adjective" },
  { word: "adequate", definition: "satisfactory or acceptable in quality or quantity", difficulty: "보통", type: "adjective" },
  { word: "apparent", definition: "clearly visible or understood; obvious", difficulty: "보통", type: "adjective" },
  { word: "complex", definition: "consisting of many different and connected parts", difficulty: "보통", type: "adjective" },
  { word: "distinct", definition: "recognizably different in nature", difficulty: "보통", type: "adjective" },
  { word: "dominant", definition: "most important, powerful, or influential", difficulty: "보통", type: "adjective" },
  { word: "evident", definition: "plain or obvious; clearly seen or understood", difficulty: "보통", type: "adjective" },
  { word: "marginal", definition: "relating to or at the edge; minor or insignificant", difficulty: "어려움", type: "adjective" },
  { word: "parallel", definition: "occurring or existing at the same time; similar", difficulty: "보통", type: "adjective" },
  { word: "potential", definition: "having or showing the capacity to develop", difficulty: "보통", type: "adjective" },
  { word: "preliminary", definition: "denoting an action preceding something more important", difficulty: "어려움", type: "adjective" },
  { word: "prevalent", definition: "widespread in a particular area at a particular time", difficulty: "어려움", type: "adjective" },
  { word: "radical", definition: "relating to the root; far-reaching; fundamental", difficulty: "보통", type: "adjective" },
  { word: "random", definition: "made or happening without method or conscious decision", difficulty: "보통", type: "adjective" },
  { word: "rare", definition: "not occurring very often; unusual", difficulty: "보통", type: "adjective" },
  { word: "relevant", definition: "closely connected or appropriate to what is being done", difficulty: "보통", type: "adjective" },
  { word: "subsequent", definition: "coming after something in time", difficulty: "어려움", type: "adjective" },
  { word: "sufficient", definition: "enough; adequate", difficulty: "보통", type: "adjective" },
  { word: "unique", definition: "being the only one of its kind; unlike anything else", difficulty: "보통", type: "adjective" },
  { word: "widespread", definition: "found or distributed over a large area", difficulty: "보통", type: "adjective" },
  
  // Academic Nouns
  { word: "phenomenon", definition: "a fact or situation that is observed to exist or happen", difficulty: "어려움", type: "noun" },
  { word: "hypothesis", definition: "a proposed explanation made on limited evidence", difficulty: "어려움", type: "noun" },
  { word: "consensus", definition: "general agreement among a group", difficulty: "어려움", type: "noun" },
  { word: "precedent", definition: "an earlier event or action serving as an example", difficulty: "어려움", type: "noun" },
  { word: "perspective", definition: "a particular attitude toward or way of regarding something", difficulty: "보통", type: "noun" },
  { word: "paradigm", definition: "a typical example or pattern of something", difficulty: "어려움", type: "noun" },
  { word: "methodology", definition: "a system of methods used in a particular area of study", difficulty: "어려움", type: "noun" },
  { word: "criterion", definition: "a principle or standard by which something is judged", difficulty: "어려움", type: "noun" },
  { word: "context", definition: "the circumstances that form the setting for an event", difficulty: "보통", type: "noun" },
  { word: "correlation", definition: "a mutual relationship or connection between things", difficulty: "어려움", type: "noun" },
  { word: "aspect", definition: "a particular part or feature of something", difficulty: "보통", type: "noun" },
  { word: "category", definition: "a class or division of things regarded as having particular shared characteristics", difficulty: "보통", type: "noun" },
  { word: "component", definition: "a part or element of a larger whole", difficulty: "보통", type: "noun" },
  { word: "concept", definition: "an abstract idea; a general notion", difficulty: "보통", type: "noun" },
  { word: "consequence", definition: "a result or effect of an action or condition", difficulty: "보통", type: "noun" },
  { word: "contemporary", definition: "living or occurring at the same time", difficulty: "보통", type: "noun" },
  { word: "entity", definition: "a thing with distinct and independent existence", difficulty: "어려움", type: "noun" },
  { word: "framework", definition: "a basic structure underlying a system or concept", difficulty: "보통", type: "noun" },
  { word: "implication", definition: "the conclusion that can be drawn from something", difficulty: "어려움", type: "noun" },
  { word: "notion", definition: "a conception or belief about something", difficulty: "보통", type: "noun" },
  { word: "principle", definition: "a fundamental truth or proposition", difficulty: "보통", type: "noun" },
  { word: "procedure", definition: "an established or official way of doing something", difficulty: "보통", type: "noun" },
  { word: "protocol", definition: "official procedure or system of rules", difficulty: "어려움", type: "noun" },
  { word: "thesis", definition: "a statement put forward as a premise to be proved", difficulty: "어려움", type: "noun" },
  { word: "theory", definition: "a system of ideas intended to explain something", difficulty: "보통", type: "noun" },
  { word: "trend", definition: "a general direction in which something is developing", difficulty: "보통", type: "noun" },
  { word: "variable", definition: "an element that may change or vary", difficulty: "보통", type: "noun" },
  
  // Advanced Verbs
  { word: "acknowledge", definition: "accept or admit the existence or truth of", difficulty: "보통", type: "verb" },
  { word: "advocate", definition: "publicly recommend or support", difficulty: "어려움", type: "verb" },
  { word: "anticipate", definition: "regard as probable; expect or predict", difficulty: "보통", type: "verb" },
  { word: "assert", definition: "state a fact or belief confidently", difficulty: "보통", type: "verb" },
  { word: "constitute", definition: "be a part of a whole; compose or form", difficulty: "어려움", type: "verb" },
  { word: "contradict", definition: "deny the truth of a statement by asserting the opposite", difficulty: "보통", type: "verb" },
  { word: "enhance", definition: "intensify, increase, or further improve the quality", difficulty: "보통", type: "verb" },
  { word: "establish", definition: "set up; create; show to be true", difficulty: "보통", type: "verb" },
  { word: "facilitate", definition: "make an action or process easy or easier", difficulty: "어려움", type: "verb" },
  { word: "undermine", definition: "erode the base or foundation; weaken", difficulty: "어려움", type: "verb" },
  { word: "reinforce", definition: "strengthen or support", difficulty: "보통", type: "verb" },
  { word: "refute", definition: "prove a statement or theory to be wrong", difficulty: "어려움", type: "verb" },
  { word: "scrutinize", definition: "examine or inspect closely and thoroughly", difficulty: "어려움", type: "verb" },
  { word: "acquire", definition: "buy or obtain; come to possess", difficulty: "보통", type: "verb" },
  { word: "assume", definition: "suppose to be the case without proof", difficulty: "보통", type: "verb" },
  { word: "conceive", definition: "form or devise in the mind", difficulty: "어려움", type: "verb" },
  { word: "confine", definition: "keep or restrict within certain limits", difficulty: "보통", type: "verb" },
  { word: "derive", definition: "obtain something from a specified source", difficulty: "보통", type: "verb" },
  { word: "diminish", definition: "make or become less", difficulty: "보통", type: "verb" },
  { word: "emerge", definition: "move out of or away from something", difficulty: "보통", type: "verb" },
  { word: "exhibit", definition: "publicly display; manifest a quality", difficulty: "보통", type: "verb" },
  { word: "generate", definition: "cause something to arise or come about", difficulty: "보통", type: "verb" },
  { word: "implement", definition: "put a decision or plan into effect", difficulty: "보통", type: "verb" },
  { word: "incorporate", definition: "take in or include as part of a whole", difficulty: "어려움", type: "verb" },
  { word: "maintain", definition: "cause or enable to continue", difficulty: "보통", type: "verb" },
  { word: "manipulate", definition: "handle or control in a skillful manner", difficulty: "어려움", type: "verb" },
  { word: "modify", definition: "make partial changes to", difficulty: "보통", type: "verb" },
  { word: "perceive", definition: "become aware of through the senses", difficulty: "보통", type: "verb" },
  { word: "persist", definition: "continue firmly in a course of action", difficulty: "보통", type: "verb" },
  { word: "presume", definition: "suppose that something is the case", difficulty: "보통", type: "verb" },
  { word: "simulate", definition: "imitate the appearance or character of", difficulty: "어려움", type: "verb" },
  { word: "suspend", definition: "temporarily prevent from continuing", difficulty: "보통", type: "verb" },
  { word: "sustain", definition: "strengthen or support physically or mentally", difficulty: "보통", type: "verb" },
  { word: "undergo", definition: "experience or be subjected to", difficulty: "보통", type: "verb" },
  { word: "undertake", definition: "commit oneself to and begin an enterprise", difficulty: "보통", type: "verb" },
  { word: "utilize", definition: "make practical and effective use of", difficulty: "보통", type: "verb" },
  { word: "violate", definition: "break or fail to comply with", difficulty: "보통", type: "verb" },
  
  // Science & Nature
  { word: "agglomeration", definition: "a mass or collection of things; an accumulation", difficulty: "어려움", type: "noun" },
  { word: "crater", definition: "a large bowl-shaped cavity in the ground", difficulty: "보통", type: "noun" },
  { word: "methane", definition: "a colorless, odorless flammable gas", difficulty: "어려움", type: "noun" },
  { word: "nitrogen", definition: "a colorless, odorless unreactive gas", difficulty: "어려움", type: "noun" },
  { word: "ammonia", definition: "a colorless gas with a characteristic pungent smell", difficulty: "어려움", type: "noun" },
  { word: "eruption", definition: "an instance of erupting or bursting forth", difficulty: "보통", type: "noun" },
  { word: "volcano", definition: "a mountain with an opening to Earth's interior", difficulty: "보통", type: "noun" },
  { word: "probe", definition: "a spacecraft designed to explore space", difficulty: "보통", type: "noun" },
  { word: "ecosystem", definition: "a biological community of interacting organisms", difficulty: "보통", type: "noun" },
  { word: "biodiversity", definition: "the variety of plant and animal life in a habitat", difficulty: "어려움", type: "noun" },
  { word: "organism", definition: "an individual animal, plant, or single-celled life form", difficulty: "보통", type: "noun" },
  { word: "species", definition: "a group of living organisms", difficulty: "보통", type: "noun" },
  
  // Economics & Society
  { word: "economy", definition: "the wealth and resources of a country or region", difficulty: "보통", type: "noun" },
  { word: "economies", definition: "the wealth and resources of a country or region", difficulty: "보통", type: "noun" },
  { word: "autonomous", definition: "having the freedom to act independently", difficulty: "어려움", type: "adjective" },
  { word: "infrastructure", definition: "basic physical systems of a country or organization", difficulty: "어려움", type: "noun" },
  { word: "capitalism", definition: "an economic system based on private ownership", difficulty: "보통", type: "noun" },
  { word: "commodity", definition: "a raw material or primary agricultural product", difficulty: "어려움", type: "noun" },
  { word: "policy", definition: "a course of action adopted by government or organization", difficulty: "보통", type: "noun" },
  
  // Literature & Arts
  { word: "narrative", definition: "a spoken or written account of connected events", difficulty: "보통", type: "noun" },
  { word: "rhetoric", definition: "the art of effective or persuasive speaking or writing", difficulty: "어려움", type: "noun" },
  { word: "allegory", definition: "a story with a hidden meaning, typically moral", difficulty: "어려움", type: "noun" },
  { word: "metaphor", definition: "a figure of speech applying a word to something it doesn't literally denote", difficulty: "보통", type: "noun" },
  { word: "aesthetic", definition: "concerned with beauty or the appreciation of beauty", difficulty: "어려움", type: "adjective" },
  
  // General Academic
  { word: "concentrate", definition: "focus attention or effort on something", difficulty: "보통", type: "verb" },
  { word: "readily", definition: "without hesitation or reluctance; willingly", difficulty: "보통", type: "adverb" },
  { word: "foster", definition: "encourage or promote the development of", difficulty: "어려움", type: "verb" },
  { word: "innovation", definition: "a new method, idea, or product", difficulty: "보통", type: "noun" },
  { word: "tradition", definition: "the transmission of customs or beliefs", difficulty: "보통", type: "noun" },
  { word: "realize", definition: "become fully aware of as a fact", difficulty: "보통", type: "verb" },
  { word: "hypothesize", definition: "put forward a hypothesis", difficulty: "어려움", type: "verb" },
  { word: "massive", definition: "extremely large or heavy", difficulty: "보통", type: "adjective" },
  { word: "evidence", definition: "facts indicating whether a belief is true", difficulty: "보통", type: "noun" },
  { word: "associate", definition: "connect in one's mind", difficulty: "보통", type: "verb" },
  { word: "impact", definition: "the effect of one thing on another", difficulty: "보통", type: "noun" },
  { word: "premise", definition: "a previous statement from which another is inferred", difficulty: "어려움", type: "noun" },
  { word: "rational", definition: "based on reason or logic", difficulty: "보통", type: "adjective" },
  { word: "theorem", definition: "a general proposition provable by reasoning", difficulty: "어려움", type: "noun" },
  { word: "thereby", definition: "by that means; as a result of that", difficulty: "보통", type: "adverb" },
  { word: "underlie", definition: "be the cause or basis of", difficulty: "어려움", type: "verb" },
  { word: "uniform", definition: "not changing in form or character", difficulty: "보통", type: "adjective" },
  { word: "valid", definition: "having a sound basis in logic or fact", difficulty: "보통", type: "adjective" },
  { word: "vary", definition: "differ in size, amount, degree, or nature", difficulty: "보통", type: "verb" },
  { word: "via", definition: "traveling through or by way of", difficulty: "보통", type: "preposition" },
  { word: "virtual", definition: "almost or nearly as described", difficulty: "보통", type: "adjective" },
  { word: "visible", definition: "able to be seen", difficulty: "보통", type: "adjective" },
  { word: "volume", definition: "the amount of space occupied by something", difficulty: "보통", type: "noun" },
  { word: "voluntary", definition: "done by one's own free will", difficulty: "보통", type: "adjective" },
  { word: "whereas", definition: "in contrast or comparison with the fact that", difficulty: "보통", type: "conjunction" },
  { word: "whereby", definition: "by which; as a result of which", difficulty: "어려움", type: "adverb" },
  
  // Additional Common SAT Words
  { word: "beneficial", definition: "resulting in good; favorable or advantageous", difficulty: "보통", type: "adjective" },
  { word: "characteristic", definition: "typical of a particular person, place, or thing", difficulty: "보통", type: "adjective" },
  { word: "coherent", definition: "logical and consistent", difficulty: "어려움", type: "adjective" },
  { word: "compatible", definition: "able to exist or occur together without conflict", difficulty: "보통", type: "adjective" },
  { word: "contrary", definition: "opposite in nature or character", difficulty: "보통", type: "adjective" },
  { word: "controversy", definition: "prolonged public disagreement or heated discussion", difficulty: "보통", type: "noun" },
  { word: "crucial", definition: "of great importance", difficulty: "보통", type: "adjective" },
  { word: "cumulative", definition: "increasing by successive additions", difficulty: "어려움", type: "adjective" },
  { word: "decline", definition: "become smaller, weaker, or less important", difficulty: "보통", type: "verb" },
  { word: "dedicate", definition: "devote time, effort to a particular purpose", difficulty: "보통", type: "verb" },
  { word: "deliberately", definition: "consciously and intentionally; on purpose", difficulty: "보통", type: "adverb" },
  { word: "demonstrate", definition: "clearly show the existence or truth of something", difficulty: "보통", type: "verb" },
  { word: "depict", definition: "show or represent by a drawing, painting, or other art form", difficulty: "보통", type: "verb" },
  { word: "elaborate", definition: "involving many carefully arranged parts", difficulty: "보통", type: "adjective" },
  { word: "eliminate", definition: "completely remove or get rid of", difficulty: "보통", type: "verb" },
  { word: "emphasize", definition: "give special importance or value to something", difficulty: "보통", type: "verb" },
  { word: "exceed", definition: "be greater in number or size than", difficulty: "보통", type: "verb" },
  { word: "exclusively", definition: "to the exclusion of others", difficulty: "보통", type: "adverb" },
  { word: "extensive", definition: "covering a large area; having a wide scope", difficulty: "보통", type: "adjective" },
  { word: "fluctuate", definition: "rise and fall irregularly in number or amount", difficulty: "어려움", type: "verb" },
  { word: "furthermore", definition: "in addition; besides", difficulty: "보통", type: "adverb" },
  { word: "immense", definition: "extremely large or great", difficulty: "보통", type: "adjective" },
  { word: "incredible", definition: "impossible to believe; extraordinary", difficulty: "보통", type: "adjective" },
  { word: "indication", definition: "a sign or piece of information that indicates something", difficulty: "보통", type: "noun" },
  { word: "inevitable", definition: "certain to happen; unavoidable", difficulty: "어려움", type: "adjective" },
  { word: "initial", definition: "existing or occurring at the beginning", difficulty: "보통", type: "adjective" },
  { word: "interact", definition: "act in such a way as to have an effect on another", difficulty: "보통", type: "verb" },
  { word: "interpretation", definition: "the action of explaining the meaning of something", difficulty: "보통", type: "noun" },
  { word: "likewise", definition: "in the same way; also", difficulty: "보통", type: "adverb" },
  { word: "mechanism", definition: "a system of parts working together", difficulty: "보통", type: "noun" },
  { word: "moreover", definition: "in addition to what has been said", difficulty: "보통", type: "adverb" },
  { word: "nevertheless", definition: "in spite of that; however", difficulty: "보통", type: "adverb" },
  { word: "objective", definition: "not influenced by personal feelings; based on facts", difficulty: "보통", type: "adjective" },
  { word: "obtain", definition: "get, acquire, or secure", difficulty: "보통", type: "verb" },
  { word: "obviously", definition: "in a way that is easily perceived or understood", difficulty: "보통", type: "adverb" },
  { word: "plausible", definition: "seeming reasonable or probable", difficulty: "어려움", type: "adjective" },
  { word: "precise", definition: "marked by exactness and accuracy", difficulty: "보통", type: "adjective" },
  { word: "predominantly", definition: "mainly; for the most part", difficulty: "어려움", type: "adverb" },
  { word: "previously", definition: "at a previous or earlier time", difficulty: "보통", type: "adverb" },
  { word: "primary", definition: "of chief importance; principal", difficulty: "보통", type: "adjective" },
  { word: "propose", definition: "put forward an idea or plan for consideration", difficulty: "보통", type: "verb" },
  { word: "remarkable", definition: "worthy of attention; extraordinary", difficulty: "보통", type: "adjective" },
  { word: "retain", definition: "continue to have something; keep possession of", difficulty: "보통", type: "verb" },
  { word: "reveal", definition: "make known to others", difficulty: "보통", type: "verb" },
  { word: "scope", definition: "the extent of the area or subject matter", difficulty: "보통", type: "noun" },
  { word: "specifically", definition: "in a way that is exact and clear", difficulty: "보통", type: "adverb" },
  { word: "structure", definition: "the arrangement of and relations between parts", difficulty: "보통", type: "noun" },
  { word: "transform", definition: "make a marked change in form or appearance", difficulty: "보통", type: "verb" },
  { word: "ultimately", definition: "finally; in the end", difficulty: "보통", type: "adverb" },
  { word: "utilize", definition: "make practical use of", difficulty: "보통", type: "verb" },
];

// Extract vocabulary from text
export const extractVocabularyFromText = (text: string, questionId: number) => {
  const foundWords = [];
  const lowerText = text.toLowerCase();

  for (const wordData of SAT_VOCABULARY) {
    // Match whole words only
    const wordPattern = new RegExp(`\\b${wordData.word.toLowerCase()}\\b`, 'i');
    if (wordPattern.test(lowerText)) {
      // Extract context (surrounding words)
      const contextMatch = text.match(new RegExp(`\\b\\w+\\s+\\w*${wordData.word}\\w*\\s+\\w+\\b`, 'i'));
      const context = contextMatch ? contextMatch[0] : wordData.word;
      
      foundWords.push({
        ...wordData,
        questionId,
        context,
        dateAdded: new Date().toISOString(),
        mastered: false,
        reviewCount: 0
      });
    }
  }

  return foundWords;
};
